version: "3.7"

services:
  web:
    build: .
    # command: gunicorn --bind 0.0.0.0:8080 properties:create_app() # Uncomment for production ready
    command: flask run --host=0.0.0.0 --port=8080
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=properties
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=postgresql://flask:flask123@db/flask
      - SECRET_KEY="dev"
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
      - GOOGLE_MAPS_API_KEY=
    volumes: 
      - ./:/usr/src/app/
    depends_on:
      - db
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=flask
      - POSTGRES_PASSWORD=flask123
      - POSTGRES_DB=flask
volumes:
  postgres_data: